<p align="center">
  <img src="https://raw.githubusercontent.com/lacamposm/Diplomado_Metodos_UCentral/main/data/images/imagen_ucentral.jpg" alt="logo_Ucentral" width="400px" height="300px">
</p>

---
# Librería `numpy`
---
`numpy` es una librería numérica de **Python** la cual será de frecuente uso. Sus propias funciones, así como el hecho que muchas librerías de **Python** estén basadas en ella, la hacen parte fundamental de la ciencía de datos. Se destaca por su velocidad y las operaciones matemáticas sobre colecciones que con ella se pueden desarrollar.

Más información [aquí.](https://numpy.org/doc/stable/index.html)

Consideremos las siguiente listas de 5 estaturas (en metros) y pesos (en kilogramos).

In [1]:
estatura = [1.73, 1.68, 1.71, 1.89, 1.79]
peso = [65.4, 59.2, 63.6, 88.4, 68.7]

El índice de masa corporal se define como:


$$IMC=\frac{peso}{estatura^{2}}$$

In [2]:
#estatura/peso**2

In [3]:
# Instalación numpy
# !pip install numpy

In [4]:
## Importamos la librería 
import numpy as np

np_estatura = np.array(estatura)
print(type(np_estatura))
print(np_estatura.shape)
np_estatura

<class 'numpy.ndarray'>
(5,)


array([1.73, 1.68, 1.71, 1.89, 1.79])

In [5]:
np_peso = np.array(peso)
np_peso

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [6]:
print(np_estatura)
print(np_estatura**2)

[1.73 1.68 1.71 1.89 1.79]
[2.9929 2.8224 2.9241 3.5721 3.2041]


In [7]:
imc = np_peso/np_estatura**2; imc

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [8]:
lista = [1,2,3]
np_lista = np.array([1,2,3],)

In [9]:
## Suma de listas
lista + lista

[1, 2, 3, 1, 2, 3]

In [10]:
## Suma de arrays
np_lista+np_lista

array([2, 4, 6])

## Subconjuntos en `numpy`

In [11]:
imc

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [12]:
imc[-1]

21.44127836209856

In [13]:
imc > 23

array([False, False, False,  True, False])

In [14]:
print(imc)
imc[imc>23]

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


array([24.7473475])

In [15]:
## Es iterable
print(imc)
for i in imc:
  print(i)
  print(type(i))

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]
21.85171572722109
<class 'numpy.float64'>
20.97505668934241
<class 'numpy.float64'>
21.750282138093777
<class 'numpy.float64'>
24.74734749867025
<class 'numpy.float64'>
21.44127836209856
<class 'numpy.float64'>


In [16]:
imc_string = imc.astype(str); imc_string

array(['21.85171572722109', '20.97505668934241', '21.750282138093777',
       '24.74734749867025', '21.44127836209856'], dtype='<U32')

### Comentario

In [17]:
prueba_np = np.array([True, True, False, False])
prueba_np.dtype

dtype('bool')

In [18]:
prueba_np1 = np.array([1, True, 2, False])
prueba_np1.dtype

dtype('int64')

In [19]:
prueba_np2 = np.array([1, True, 3, np.pi])
prueba_np2.dtype

dtype('float64')

In [20]:
prueba_np3 = np.array([1, True, 'hola', np.pi])
prueba_np3.dtype

dtype('<U32')

## Ejercicio 1.

Importe el paquete `numpy` como `np`, cree un `np.array()` que será un arreglo numérico de la siguiente lista, imprima el arreglo y el tipo de dato.

~~~python
ciclismo = [180, 215, 210, 210, 188, 176, 209, 200]
~~~


**Respuesta.**

In [21]:
## Acá su código
import numpy as np
ciclismo = [180, 215, 210, 210, 188, 176, 209, 200]
np_ciclismo = np.array(ciclismo)
print(np_ciclismo)
print(type(np_ciclismo))

[180 215 210 210 188 176 209 200]
<class 'numpy.ndarray'>


## Ejercicio 2

Transforme las estaturas a pulgadas dividiendo por 0.0254.

**Respuesta:**

In [22]:
np_estatura

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [23]:
## Su código acá
pulgadas = np_estatura/0.0254
pulgadas

array([68.11023622, 66.14173228, 67.32283465, 74.40944882, 70.47244094])

## Ejercicio 3

Creamos alturas y pesos:
~~~python
mis_pesos = np.random.normal(70.5,20,10)
mis_alturas = np.random.normal(1.60,10,10)
~~~
Calcular el imc.

**Respuesta**

In [24]:
## Su código acá
np.random.seed(123)
mis_pesos = np.random.normal(70.5, 20, 10)
mis_alturas = np.random.normal(1.70, 0.1, 10)

In [25]:
mis_alturas

array([1.63211138, 1.6905291 , 1.84913896, 1.6361098 , 1.6556018 ,
       1.65656487, 1.92059301, 1.91867861, 1.80040539, 1.73861864])

---
## `n-numpy arrays`
---

Los `numpy arrays` son arreglos numéricos similares a las matrices.

In [26]:
np_1d = np.array([10,20,25,30,60])
print(np_1d)
np_1d.shape

[10 20 25 30 60]


(5,)

In [27]:
## Arreglo de 5 entradas (se puede ver como un vector)
type(np_1d), np_1d.shape

(numpy.ndarray, (5,))

In [28]:
## Arreglo de 2 dimensiones (se pueden considerar como matrices)
np_2d = np.array([
    [1.73, 1.68, 1.71, 1.89, 1.79],
    [65.4, 59.2, 63.6, 88.4, 68.7]
    ])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [29]:
type(np_2d), np_2d.shape

(numpy.ndarray, (2, 5))

In [30]:
## Debe tener el mismo tipo de dato.
np.array([
    [1.73, 1.68, 1.71, 1.89, 1.79],
    [65.4, 59.2, 63.6, 88.4, '68.7']
    ])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

In [31]:
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [32]:
np_2d[0], type(np_2d[0]), np_2d[0].shape

(array([1.73, 1.68, 1.71, 1.89, 1.79]), numpy.ndarray, (5,))

In [33]:
for i in np_2d[0]:
  print(i)

1.73
1.68
1.71
1.89
1.79


In [34]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [35]:
np_2d[1]

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [36]:
#np_2d[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [37]:
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [38]:
print(np_2d[:1].shape)
np_2d[:2]

(1, 5)


array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [39]:
for i in np_2d[:1]:
  print(i)

[1.73 1.68 1.71 1.89 1.79]


In [40]:
## Primera fila
np_2d[0, :]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [41]:
## Segunda fila
np_2d[1, :]

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [42]:
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [43]:
np_2d[1, 0:2]

array([65.4, 59.2])

In [44]:
## Elemento 0,0 en Python del arreglo.
np_2d[0][0], np_2d[0,0]

(1.73, 1.73)

In [45]:
## Todas las filas y las columnas 1 y 2 en Python
np_2d[:, 1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [46]:
## Arreglo de 3 compomentes de arreglos 2x5
np_3d = np.array([
    [[1.73, 1.68, 1.71, 1.89, 1.79],
     [65.4, 59.2, 63.6, 88.4, 68.7]],
    [[1.85, 1.68, 1.71, 1.89, 1.79],
     [65.4, 59.2, 85.3, 88.4, 68.7]],
    [[1.90, 1.15, 1.81, 1.89, 1.79],
     [69.4, 68.1, 70.6, 88.4, 200.7]]
     ])
np_3d

array([[[  1.73,   1.68,   1.71,   1.89,   1.79],
        [ 65.4 ,  59.2 ,  63.6 ,  88.4 ,  68.7 ]],

       [[  1.85,   1.68,   1.71,   1.89,   1.79],
        [ 65.4 ,  59.2 ,  85.3 ,  88.4 ,  68.7 ]],

       [[  1.9 ,   1.15,   1.81,   1.89,   1.79],
        [ 69.4 ,  68.1 ,  70.6 ,  88.4 , 200.7 ]]])

In [47]:
type(np_3d), np_3d.shape

(numpy.ndarray, (3, 2, 5))

### ***Operaciones con matrices.***

In [48]:
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [49]:
## Transpuesta
print(np_2d)
np_2d.transpose()

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]


array([[ 1.73, 65.4 ],
       [ 1.68, 59.2 ],
       [ 1.71, 63.6 ],
       [ 1.89, 88.4 ],
       [ 1.79, 68.7 ]])

In [50]:
## Producto de matriz
A = np_2d
A_t = np_2d.transpose()

## A_t multiplicación de matrices (@) con A
print(A.shape)
print(A_t.shape)
A_t@A

(2, 5)
(5, 2)


array([[4280.1529, 3874.5864, 4162.3983, 5784.6297, 4496.0767],
       [3874.5864, 3507.4624, 3767.9928, 5236.4552, 4070.0472],
       [4162.3983, 3767.9928, 4047.8841, 5625.4719, 4372.3809],
       [5784.6297, 5236.4552, 5625.4719, 7818.1321, 6076.4631],
       [4496.0767, 4070.0472, 4372.3809, 6076.4631, 4722.8941]])

In [51]:
## Como un método de numpy.
np.dot(A_t, A)

array([[4280.1529, 3874.5864, 4162.3983, 5784.6297, 4496.0767],
       [3874.5864, 3507.4624, 3767.9928, 5236.4552, 4070.0472],
       [4162.3983, 3767.9928, 4047.8841, 5625.4719, 4372.3809],
       [5784.6297, 5236.4552, 5625.4719, 7818.1321, 6076.4631],
       [4496.0767, 4070.0472, 4372.3809, 6076.4631, 4722.8941]])

In [52]:
## Matriz de ceros
np.zeros((3,4),)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
## Matriz identidad
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
## 100  equidistantes entre 10 y 50
np.linspace(start=10, stop=50, num=100)

array([10.        , 10.4040404 , 10.80808081, 11.21212121, 11.61616162,
       12.02020202, 12.42424242, 12.82828283, 13.23232323, 13.63636364,
       14.04040404, 14.44444444, 14.84848485, 15.25252525, 15.65656566,
       16.06060606, 16.46464646, 16.86868687, 17.27272727, 17.67676768,
       18.08080808, 18.48484848, 18.88888889, 19.29292929, 19.6969697 ,
       20.1010101 , 20.50505051, 20.90909091, 21.31313131, 21.71717172,
       22.12121212, 22.52525253, 22.92929293, 23.33333333, 23.73737374,
       24.14141414, 24.54545455, 24.94949495, 25.35353535, 25.75757576,
       26.16161616, 26.56565657, 26.96969697, 27.37373737, 27.77777778,
       28.18181818, 28.58585859, 28.98989899, 29.39393939, 29.7979798 ,
       30.2020202 , 30.60606061, 31.01010101, 31.41414141, 31.81818182,
       32.22222222, 32.62626263, 33.03030303, 33.43434343, 33.83838384,
       34.24242424, 34.64646465, 35.05050505, 35.45454545, 35.85858586,
       36.26262626, 36.66666667, 37.07070707, 37.47474747, 37.87

---
## En análisis de datos
---

In [55]:
np.random.seed(123)
estaturas = np.round(np.random.normal(1.75, 0.20, 5000), 4)
pesos = np.round(np.random.normal(60.32, 15, 5000), 4)
np_bogota = np.column_stack((estaturas, pesos))

In [56]:
## Arreglo de dimensión 5000x2
np_bogota, np_bogota.shape

(array([[ 1.5329, 65.1015],
        [ 1.9495, 82.9866],
        [ 1.8066, 43.2706],
        ...,
        [ 1.3781, 53.236 ],
        [ 1.9328, 69.0495],
        [ 1.4792, 74.8792]]),
 (5000, 2))

In [57]:
np_bogota[0:5,:]

array([[ 1.5329, 65.1015],
       [ 1.9495, 82.9866],
       [ 1.8066, 43.2706],
       [ 1.4487, 69.9569],
       [ 1.6343, 43.4018]])

In [58]:
## Media
np.mean(np_bogota[:,0])

1.7542166000000001

In [59]:
## Mediana
np.median(np_bogota[:,1])

60.23525

In [60]:
## Los tres cuartiles de la variable estatura.
np.quantile(np_bogota[:,0], [0, 0.25, 0.50, 0.75, 1])

array([0.9897  , 1.6198  , 1.7559  , 1.887625, 2.4643  ])

In [61]:
## Desviación estandar
np.std(np_bogota[:,0])

0.1975540062272593

In [62]:
## Matriz de Covarianzas
np.corrcoef(np_bogota[:,0], np_bogota[:,1])

array([[1.        , 0.00212582],
       [0.00212582, 1.        ]])

## ***En algebra lineal.***

In [63]:
## Producto de matrices

A = np.array([[5, 3, 6, -5],
              [-3, 0.5, 9, 22],
              [-9, 5, 0, 3],
              [5, -6, -1.5, 2]])

print(f'Dado que el determinante de la matriz A es: {np.linalg.det(A):.2f}, la matriz es invertible')

Dado que el determinante de la matriz A es: 991.50, la matriz es invertible


In [64]:
## Resolvemos sistemAs de ecuAciones Ax = b
b = np.array([1, 5, 8, 9])
##
x = np.linalg.solve(A, b); x

array([-15.86762481, -21.86535552,  17.24407463,  -8.49394856])

In [65]:
np.allclose(np.dot(A, x), b)

True

## ***Valores y vectores propios.***

In [66]:
A

array([[ 5. ,  3. ,  6. , -5. ],
       [-3. ,  0.5,  9. , 22. ],
       [-9. ,  5. ,  0. ,  3. ],
       [ 5. , -6. , -1.5,  2. ]])

In [67]:
## Valores y vectores propios.

eigenvalues, eigenvectors = np.linalg.eig(A)

In [68]:
eigenvalues

array([3.4631373+13.1008915j , 3.4631373-13.1008915j ,
       0.2868627 +2.30591674j, 0.2868627 -2.30591674j])

In [69]:
eigenvectors

array([[-0.34254317-0.32565231j, -0.34254317+0.32565231j,
         0.48179976+0.14340771j,  0.48179976-0.14340771j],
       [ 0.56588578+0.j        ,  0.56588578-0.j        ,
         0.62488102+0.j        ,  0.62488102-0.j        ],
       [ 0.40304226-0.31375016j,  0.40304226+0.31375016j,
        -0.51928543+0.10693622j, -0.51928543-0.10693622j],
       [-0.1353733 +0.4209274j , -0.1353733 -0.4209274j ,
         0.27208103+0.04130549j,  0.27208103-0.04130549j]])

In [70]:
## Verificación.  Av = \lambda*v
lambda_0 = eigenvalues[0]
eigen_vec_0 = eigenvectors[:, 0]
##
print(np.dot(A, eigen_vec_0))               ## Av
print(np.dot(lambda_0, eigen_vec_0))        ## \lambda*v

[ 3.08006154-5.61539953j  1.95974017+7.41360826j  5.50619753+4.19365298j
 -5.98334052-0.31578149j]
[ 3.08006154-5.61539953j  1.95974017+7.41360826j  5.50619753+4.19365298j
 -5.98334052-0.31578149j]


In [71]:
np.allclose(np.dot(A, eigen_vec_0), np.dot(lambda_0, eigen_vec_0))

True